### ISSUE TITLE
Feature: Label displaying on TitleCase

### ISSUE THREAD

**Issue by taniasg** [ShankyTiwari/ng-material-multilevel-menu#160]
The component automatically transform the string to titleCase. 
There's a way where we can set how the label is displayed? Like angular pipes
1. lowerCase.
2. upperCase
3. tittleCase
4. capitalize

**Comment by nielcleo** [comment]
Hi taniasg,

yes by using custom template you may use angular pipes.
for your reference you may check this [documentation](https://www.npmjs.com/package/ng-material-multilevel-menu#3-building-custom-templates)

cheers!

**Comment by ShankyTiwari** [comment]
Hi, @taniasg Sorry for the delay. From your question, I assume you are using the default List. So in this case you can use a custom class name and use that to apply Stylings as shown below,

**app.component.css:**
```css
::ng-deep .my-custom-class .anml-link {
  text-transform: lowerCase !important;
}
```
 
OR

**style.css:**
```css
.my-custom-class .anml-link {
  text-transform: lowerCase !important;
}
```
Just in case if you are planning to write your template then you have to take care of styling and animation on your own as @nielcleo said.

Please let me know if anything is not working for you.

Thanks
