### ISSUE TITLE
On collapse Can I show only icons?

### ISSUE THREAD

**Issue by anushapadakanti** [ShankyTiwari/ng-material-multilevel-menu#22]
Currently on collapse complete side nav visibility is hidden.
Can I show only the Icons on collapse?

**Comment by ShankyTiwari** [comment]
Hi @anushapadakanti ,
I didn't catch you here! Are you looking for something [like this](https://www.codeply.com/go/ecE6qHNBOC)?

Thanks,

**Comment by anushapadakanti** [comment]
Yes exactly,even if I resize window also it should show icon 
Is this possible with this  plugin ?

Thanks in advance

**Comment by ShankyTiwari** [comment]
Hi,
No, it's not possible using configuration settings. But you can use below CSS to hide `label `and `arrow`, the normal functionality will works as expected.
```css
.custom-class-name .label {
  display: none !important;
}

.custom-class-name .anml-data ~ mat-icon {
  display: none !important;
}
```

You can CSS Media queries in case window resize, as shown below,

```css
@media (max-width: 1140px) {
  .custom-class-name .label {
    display: initial !important;
  }

  .custom-class-name .anml-data ~ mat-icon {
    display: initial !important;
  }
}

@media (max-width: 400px) {
  .custom-class-name .label {
    display: none !important;
  }

  .custom-class-name .anml-data ~ mat-icon {
    display: none !important;
  }
}
```
Though I haven't tested this code, but it should work.
Thanks,
