### ISSUE TITLE
remove  border-top-style mat-divider, cursor pointer, routerlink

### ISSUE THREAD

**Issue by lwazevedo** [ShankyTiwari/ng-material-multilevel-menu#3]
Hi, 

Can not get border-top-style and border-whidth and border-top-color of component mat-divider?

I've tried these ways:

.```
mat-divider {
    border-top-width: 0px! important;
    border-top-style: none! important;
}
```

and

```
.mat-divider.mat-divder-inset {
    border-top-width: 0px! important;
    border-top-style: none! important;
}

```
Also it is not possible to modify the pointer cursor?

.class-custom {
    cursor: pointer
}

Is it also not possible to use routelink?

Thank you.

**Comment by ShankyTiwari** [comment]
Hi there,
You give your custom class name( shown below) and modify the styling according to need
```typescript
config = {
    paddingAtStart: true,
    classname: 'my-custom-class'
  };

```
=> If you don't want `<mat-divider>` border, then do something like this in your style.css file,
```css
.my-custom-class .mat-divider{
    border-top-style: none !important;
}
```

=> In order to modify the cursor, in your style.css file,
```css
.my-custom-class .amml-item{
    cursor: pointer;
}
```

=> Is it also not possible to use routelink?
Sorry, it's not supported, you'll have to manage it on your own.

If something doesn't work, clone [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo).
Thanks.
